build:
  nodes:
    analysis:
      project_setup:
        override:
          - 'true'
      tests:
        override:
          - php-scrutinizer-run
          -
            command: phpcs-run
            use_website_config: true
      environment:
        node:
          version: 6.0.0
    tests: true
  filter:
    excluded_paths:
      - 'tests/*'
  checks:
    php: true
  coding_style:
    php:
      spaces:
        around_operators:
          unary_additive: true
          concatenation: true
          negation: true
        within:
          brackets: true
  environment:
    php:
      version: "7.1.0"
  dependencies:
    before:
      - composer self-update
      - composer install --prefer-source --no-interaction --dev
      - vendor/bin/phplint
  tests:
    override:
      -
        command: 'vendor/bin/phpunit --coverage-clover=clover'
        coverage:
          file: 'clover'
          format: 'clover'
