language: php

php:
  - '5.6.4'
  - '7.0'
  - '7.1'
  - '7.2'

before_script:
  - composer self-update
  - composer install --prefer-srouce --no-interaction --dev
  - vendor/bin/phplint

script:
  - vendor/bin/phpunit

matrix:
  fast_finish: true
